### ISSUE TITLE
ImportError:  name 'ABCIndexClass' from 'pandas.core.dtypes.generic'

### ISSUE THREAD

**Issue by madpower2000** [mljar/studio#74]
Fresh installation from MLJAR-Studio-Setup-1.0.0.exe on Windows 10 Pro 21H1.
```
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from pandas_profiling import ProfileReport
from supervised import AutoML
```
After creating new notebook got ImportError:
`cannot import name 'ABCIndexClass' from 'pandas.core.dtypes.generic' (C:\Users\...\AppData\Roaming\MLJAR-Studio\miniconda\lib\site-packages\pandas\core\dtypes\generic.py)`

![image](https://user-images.githubusercontent.com/22916407/141805512-81d07fff-01ed-496c-865c-f1db4794ff63.png)

**Comment by pplonski** [comment]
Sorry about the problem.

I've searched a little and looks like a problem similar to this one https://stackoverflow.com/questions/68704002/importerror-cannot-import-name-abcindexclass-from-pandas-core-dtypes-generic

Please try comment `# from pandas_profiling import ProfileReport` and then click `Run` button. It will not import pandas_profiling package which is causing a problem.

Next solution might be trying to downgrade pandas to 1.2.5. Please run in the new Python cell:
```
conda install -c conda-forge pandas=1.2.5 -y
```

**Comment by madpower2000** [comment]
Yes, after edititng  file "~/[your_conda_env_path]/lib/site-packages/visions/dtypes/boolean.py" as was sugested stackoverflow.com,  the import problem was fixed. But I was hoping the product would work right after installation, without the need for voodoo spells....

**Comment by pplonski** [comment]
I will fix this for next release, so it will work out of the box.

**Comment by Padmanaabhah** [comment]
How do we fix this in colab. any help

**Comment by pplonski** [comment]
@Padmanaabhah are you trying to use pandas profiling?

**Comment by Padmanaabhah** [comment]
> @Padmanaabhah are you trying to use pandas profiling?

Yes im in Google colab.

**Comment by pplonski** [comment]
Please to downgrade or upgrade pandas profiling package

**Comment by Padmanaabhah** [comment]
> Please to downgrade or upgrade pandas profiling package

to what version please

**Comment by pplonski** [comment]
You need to check that yourself in their github repo. It is an issue with pandas profiling not studio.

**Comment by aksweb** [comment]
> > Please to downgrade or upgrade pandas profiling package
> 
> to what version please



> How do we fix this in colab. any help

hey, did you able to solve it on colab?
